### ISSUE TITLE
Global Caching Not Working with context.newPage()

### ISSUE THREAD

**Issue by YuryMishin** [vitalets/playwright-network-cache#3]
Hello, Vitaliy Potapov

I'm encountering an issue with global caching in playwright-network-cache. Despite setting up global caching as recommended, it doesn’t apply to tests using either context.newPage() or browser.newPage(). The caching only works on initial page loads without these methods.

Here's a simplified version of my caching setup:

```
export const test = (playwrightTest).extend<{
  cacheRoute: CacheRoute
}>({
  cacheRoute: [async ({ page }, use) => {
    const cacheRoute = new CacheRoute(page, { ttlMinutes: 60 * 6 });
    await cacheRoute.GET('/api/v1/**', {
      extraDir: req => {
        const url = new URL(req.url());
        const params = Object.fromEntries(new URLSearchParams(url.search));
        return CryptoJS.MD5(JSON.stringify(params)).toString();
      },
    });
    await use(cacheRoute);
  }, { auto: true }]
});
```
With this setup, the cache functions as expected only on the initial page load. However, as soon as I use context.newPage() or browser.newPage() to create a new page, caching no longer works for those requests.

Is there a way to apply caching globally across all pages, including those created with context.newPage() and browser.newPage()? Or could this be a limitation of the current caching implementation?

Thank you for any insights or recommendations!

**Comment by vitalets** [comment]
Hey! For `context` it works, you can pass `context` instead of `page`:
```ts
cacheRoute: [async ({ context }, use) => {
    const cacheRoute = new CacheRoute(context, { ttlMinutes: 60 * 6 });
    await cacheRoute.GET(...);
    await use(cacheRoute);
  }, { auto: true }]
```
It's good catch, I will update the docs.

For the whole browser: Playwright does not provide an API to automatically hook requests for all new contexts of a browser. So here we can only attach cache manually:
```ts
const page = await browser.newPage();
const cacheRoute = new CacheRoute(page, { ttlMinutes: 60 * 6 });
await cacheRoute.GET(...);
```
I think it can be wrapped into a helper if often needed:
```ts
async function newPage(browser: Browser) {
  const page = await browser.newPage();
  const cacheRoute = new CacheRoute(page, { ttlMinutes: 60 * 6 });
  await cacheRoute.GET(...);
  return page;
}
```
